language: java
deploy:
  provider: cloudfoundry
  username: sundara2803@gmail.com
  password: Chainsys@2020
  api: https://api.run.pivotal.io
  organization: cricketauctionapp
  space: development
  manifest: manifest.yml
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install